[package]
name = "quantum-tetris-quantum"
description = "Circuits and backends for Quantum Tetris"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rand = "0.9"
qip = "1.5.0"

[dev-dependencies]
serde_json = { workspace = true }

[features]
default = []
